package com.salarybox.app.util

import kotlin.math.sqrt

/**
 * Utility for comparing Face embeddings generated by MobileFaceNet.
 */
object FaceMatcher {
    
    /**
     * 0.75f is a heuristic threshold for cosine similarity.
     * This should be tuned with real test data. A higher threshold reduces false positives,
     * while a lower threshold reduces false negatives.
     */
    const val MATCH_THRESHOLD = 0.75f
    
    fun matches(embedding1: FloatArray, embedding2: FloatArray, threshold: Float = MATCH_THRESHOLD): Boolean {
        return cosineSimilarity(embedding1, embedding2) >= threshold
    }

    fun cosineSimilarity(a: FloatArray, b: FloatArray): Float {
        var dotProduct = 0.0f
        var normA = 0.0f
        var normB = 0.0f
        for (i in a.indices) {
            dotProduct += a[i] * b[i]
            normA += a[i] * a[i]
            normB += b[i] * b[i]
        }
        return if (normA == 0.0f || normB == 0.0f) 0.0f else dotProduct / (sqrt(normA) * sqrt(normB))
    }
    
    // Simple helper to parse the comma-separated string back to FloatArray
    fun parseEmbedding(encoded: String): FloatArray {
        return encoded.split(",").map { it.toFloat() }.toFloatArray()
    }
    
    // Simple helper to format the FloatArray to a comma-separated string
    fun encodeEmbedding(embedding: FloatArray): String {
        return embedding.joinToString(",")
    }
}
